theme: jekyll-theme-minimal
title: Every problem is an equation and optimisation problem.
description: Dives into computational rethinking of problems in diverse domains, from chemistry and physics to society and architecture, archelogical liguistics to workforce productivity maximisation, model can be developed for most problems and the associated master/objective equation can be solved/optimised.
timezone : Europe/Paris
baseurl: ./about.html