domain: swaroopkunapuli.github.io
url: https://swaroopkunapuli.github.io
ignore_theme_config: TRUE
title: Swaroop's work and interests
description: I am trying to work on my thesis project and my interests, data analysis for equitable representation in democratic systems. I will keep you updated as I keep going!
